spring:
  datasource:
    hikari:
      username:
      password:
    url: jdbc:mysql://localhost:3306/timeline?useSSL=false&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
oss:
  endpoint: oss-cn-shanghai.aliyuncs.com
  accessKeyId:
  accessKeySecret:
  bucketName: